import type { Metadata } from "next";
import "@/app/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        {/* TODO: サイドバーを実装する
          widthを変えるよりもgridレイアウトに変えるほうがいいかも
        */}
        <main className="mx-auto lg:w-4/5 xl:w-2/3 2xl:w-3/5">{children}</main>
    </>
  );
}
