import type { Metadata } from "next";
import "@/app/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <>{children}</>
        <footer>
          <p>© {new Date().getFullYear()} Bunbun</p>
          <p>Built date: {new Date().toLocaleString("ja-JP", {timeZone: "Asia/Tokyo"})}</p>
          <p>
            ソースコード:{" "}
            <a href="https://github.com/tamago572/bunbun-blog-renewed">
              GitHub
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
